<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

namespace HuynhTest\Example;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>example.DelResponse</code>
 */
class DelResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool OK = 1;</code>
     */
    protected $OK = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $OK
     * }
     */
    public function __construct($data = NULL) {
        \HuynhTest\Example\Meta\Example::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool OK = 1;</code>
     * @return bool
     */
    public function getOK()
    {
        return $this->OK;
    }

    /**
     * Generated from protobuf field <code>bool OK = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setOK($var)
    {
        GPBUtil::checkBool($var);
        $this->OK = $var;

        return $this;
    }

}

